FROM python:3-alpine

RUN apk add --no-cache mariadb-dev build-base

COPY microservice1 /microservice1

WORKDIR /microservice1

RUN pip install -r requirements.txt

CMD ["python", "microservice1.py"]
